name: Deploy Hasura

on: workflow_dispatch

jobs:
  deploy-hasura:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install packages
        uses: borales/actions-yarn@v3.0.0

      - name: deploy-hasura
        run: |
          yarn hasura migrate apply --endpoint http://www.varekai-pizza.art/ --admin-secret ${{ secrets.HASURA_ADMIN_SECRET }} 
           --database-name default
          yarn hasura metadata apply --endpoint http://www.varekai-pizza.art/ --admin-secret ${{ secrets.HASURA_ADMIN_SECRET }}
